name: NezEconomy
main: com.neztec.NezEconomyPlugin
version: "1.0.0"
api: "2.0.0"
load: STARTUP
author: Nayisw
description: The best economy plugin for PowerNukkitX 2.0
website: https://github.com/NeztecNetwork/NezEconomyc